// parameters.hpp — generated by the CRISP KV260 integer exporter; the HLS core and the oracle share these constants.
// package 344b5f19  ckpt c9464dfee637d4a6  data a1af6da28169  oracle_md5 7a904563879ad7030deb021476869beb
#ifndef HW_PARAMS_H
#define HW_PARAMS_H
#define HW_T 100
#define HW_N_IN 700
#define HW_H 256
#define HW_C 20
#define HW_K 8
#define HW_P 8
#define HW_WB 8
#define HW_CB 18
#define HW_FA 16
#define HW_FS 12
#define HW_FZ 8
#define HW_NB 12
#define HW_SB 11
#define HW_M 256
#define HW_DENOM_SEQ 5000
#define HW_DENOM_FIX 1000
#define HW_SHC1 (9)
#define HW_SHC2 (9)
#define HW_SHCRO (12)
#define HW_N_LOOKS 5
#define HW_LOOKS {16, 32, 64, 128, 256}
#define HW_WU1 17
#define HW_WS 24
#define HW_WU2 16
#define HW_WU2_MF 21
#define HW_WR 16
#define HW_WR_MF 23
#define HW_WRS 24
#define HW_WL 32
#define HW_N_TEST 2264
#define HW_NEV_MAX 12788
#define HW_NEV_TOTAL 14167487
#define HW_PACKAGE_ID 0x344b5f19u
#endif
